---
title: "script projet"
output: github_document
---
title: "projet ADM"
output: github_document
---
commande bash dans le terminal:
ls= list show, montre ce qu'il y a dans le dossier (dans le terminal)
|= (le « pipe ») envoie cette sortie à la commande suivante
wc=word count (word count, option -l pour lines) compte le nombre de lignes reçues
, -l= lignes, 
ls | wc -l 

```{r}
library(dada2); packageVersion("dada2")
```

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ShortRead", version = "3.23") 
```


```{r}
metadata <- read.csv("SraRunTable.csv", header = TRUE, sep=",")
View(metadata)
```

```{r}
path <- "/home/rstudio/Projet ADM/Script projet/data projet"
```

```{r}
fnFs <- sort(list.files(path, pattern="_1.fastq.gz", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_2.fastq.gz", full.names = TRUE))
```

```{r}
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
```

```{r}
plotQualityProfile(fnFs[1:2])
```

```{r}
plotQualityProfile(fnRs[1:2])
```

```{r}
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
```

```{r}
length(fnFs); length(fnRs)
length(filtFs); length(filtRs)

# Comparer les noms d'échantillons
sample.names.F <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
sample.names.R <- sapply(strsplit(basename(fnRs), "_"), `[`, 1)
identical(sample.names.F, sample.names.R)

# Voir ce qui diffère
setdiff(sample.names.F, sample.names.R)
setdiff(sample.names.R, sample.names.F)
```

```{r}
path <- "/home/rstudio/Projet ADM/Script projet/data projet"

fnFs <- sort(list.files(path, pattern = "_1.fastq.gz", full.names = TRUE))
fnRs <- sort(list.files(path, pattern = "_2.fastq.gz", full.names = TRUE))

sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)

filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
```

```{r}
list.files(path)   # regardez à quoi ressemblent les noms de fichiers
basename(fnFs)
basename(fnRs)
```

```{r}
fichiers <- list.files(path, pattern = "\\.fastq\\.gz$")
runs <- unique(sub("_[12]\\.fastq\\.gz$", "", fichiers))
attendus <- c(paste0(runs, "_1.fastq.gz"), paste0(runs, "_2.fastq.gz"))
setdiff(attendus, fichiers)
```

```{r}
library(dada2)

path <- "/home/rstudio/Projet ADM/Data-projet-ADM/data"   # à adapter

# 1. Lister les fichiers (sans aller dans le dossier filtered/)
fnFs <- sort(list.files(path, pattern = "_1.fastq.gz$", full.names = TRUE))
fnRs <- sort(list.files(path, pattern = "_2.fastq.gz$", full.names = TRUE))

# 2. Noms d'échantillons
sample.names.F <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
sample.names.R <- sapply(strsplit(basename(fnRs), "_"), `[`, 1)

# 3. Vérifications : tout doit être OK avant de continuer
length(fnFs); length(fnRs)                     # deux nombres identiques
identical(sample.names.F, sample.names.R)      # TRUE
stopifnot(identical(sample.names.F, sample.names.R))

sample.names <- sample.names.F

# 4. Fichiers de sortie filtrés
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names

# 5. Filtrage
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs,
                     truncLen = c(260, 260),
                     maxN = 0, maxEE = c(2, 2), truncQ = 2,
                     rm.phix = TRUE, compress = TRUE, multithread = FALSE)
head(out)
```

```{r}
errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)
plotErrors(errF, nominalQ=TRUE)
```

```{r}
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
dadaFs[[1]]
```
```{r}
mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
# Inspect the merger data.frame from the first sample
head(mergers[[1]])
```
```{r}
seqtab <- makeSequenceTable(mergers)
dim(seqtab)
# Inspect distribution of sequence lengths
table(nchar(getSequences(seqtab)))
```
```{r}
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)
sum(seqtab.nochim)/sum(seqtab)
```

```{r}
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
# If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)
```

